CREATE TABLE DIM_TIEMPO(
    SK_TIEMPO NUMERIC NOT NULL,
    COD_ANIO NUMERIC NOT NULL,
    COD_TRIMESTRE NUMERIC NOT NULL,
    DES_TRIMESTRE VARCHAR(100) NOT NULL,
    COD_MES NUMERIC NOT NULL,
    DESC_MES VARCHAR(20) NOT NULL,
    DESC_MES_CORTA VARCHAR(20) NOT NULL,
    COD_SEMANA NUMERIC NOT NULL,
    COD_DIA_ANIO NUMERIC NOT NULL,
    COD_DIA_MES NUMERIC NOT NULL,
    COD_DIA_SEMANA NUMERIC NOT NULL,
    DESC_DIA_SEMANA VARCHAR(100) NOT NULL,
    FECHA DATE NOT NULL,

    CONSTRAINT CNST_SK_TIEMPO PRIMARY KEY(SK_TIEMPO)
);

CREATE TABLE DIM_SEDE(
    SK_SEDE NUMERIC NOT NULL,
    COD_PAIS NUMERIC NOT NULL,
    NB_PAIS VARCHAR(100) NOT NULL,
    COD_CIUDAD NUMERIC NOT NULL,
    NB_CIUDAD VARCHAR(100) NOT NULL,
    COD_SEDE NUMERIC NOT NULL,
    NB_SEDE VARCHAR(100) NOT NULL,

    CONSTRAINT CNST_SK_SEDE PRIMARY KEY(SK_SEDE)
);

CREATE TABLE DIM_EVENTO(
    SK_EVENTO NUMERIC NOT NULL,
    COD_TIPO_EVENTO NUMERIC NOT NULL,
    NB_TIPO_EVENTO VARCHAR(100) NOT NULL,
    COD_EVENTO NUMERIC NOT NULL,
    NB_EVENTO VARCHAR(100) NOT NULL,
    DESCRIPCION VARCHAR(100) NOT NULL,

    CONSTRAINT CNST_SK_EVENTO PRIMARY KEY(SK_EVENTO)
);

CREATE TABLE DIM_TIPO_STAND(
    SK_TIPO_STAND NUMERIC NOT NULL,
    COD_TIPO_STAND NUMERIC NOT NULL,
    NB_TIPO_STAND VARCHAR(100) NOT NULL,

    CONSTRAINT CNST_SK_TIPO_STAND PRIMARY KEY(SK_TIPO_STAND)
);

CREATE TABLE DIM_VISITANTE(
    SK_VISITANTE NUMERIC NOT NULL,
    COD_VISITANTE NUMERIC NOT NULL,
    CEDULA NUMERIC NOT NULL,
    NB_VISITANTE VARCHAR(100) NOT NULL,
    SEXO VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,

    CONSTRAINT CNST_SK_VISITANTE PRIMARY KEY(SK_VISITANTE)
);

CREATE TABLE DIM_CLIENTE(
    SK_CLIENTE NUMERIC NOT NULL,
    COD_CLIENTE NUMERIC NOT NULL,
    CI_RIF VARCHAR(100) NOT NULL,
    NB_CLIENTE VARCHAR(100) NOT NULL,
    TELEFONO VARCHAR(100) NOT NULL,
    DIRECCION VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,

    CONSTRAINT CNST_SK_CLIENTE PRIMARY KEY(SK_CLIENTE)
);

CREATE TABLE DIM_LEYENDA(
    SK_LEYENDA NUMERIC NOT NULL,
    COD_LEYENDA NUMERIC NOT NULL,
    NB_LEYENDA VARCHAR(100) NOT NULL,

    CONSTRAINT CNST_SK_LEYENDA PRIMARY KEY(SK_LEYENDA)
);

CREATE TABLE DIM_CATEGORIA(
    SK_CATEGORIA NUMERIC NOT NULL,
    COD_SUBCATEGORIA NUMERIC NOT NULL,
    NB_SUBCATEGORIA VARCHAR(100) NOT NULL,
    COD_CATEGORIA NUMERIC NOT NULL,
    NB_CATEGORIA VARCHAR(100) NOT NULL,

    CONSTRAINT CNST_SK_CATEGORIA PRIMARY KEY(SK_CATEGORIA)
);

CREATE TABLE FACT_EVENTO(
    SK_EVENTO NUMERIC NOT NULL,
    SK_SEDE NUMERIC NOT NULL,
    SK_FEC_EVENTO NUMERIC NOT NULL,
    CANTIDAD_EVENTO NUMERIC NOT NULL,
    CANTIDAD_ESTIM_VISITANTES NUMERIC NOT NULL,
    META_INGRESO NUMERIC(10,4) NOT NULL,

    CONSTRAINT CNST_PK_EVENTO PRIMARY KEY(SK_EVENTO, SK_SEDE, SK_FEC_EVENTO),
    CONSTRAINT CNST_FK_EVENTO_DIM_EVENTO FOREIGN KEY(SK_EVENTO) REFERENCES DIM_EVENTO(SK_EVENTO),
    CONSTRAINT CNST_FK_EVENTO_DIM_SEDE FOREIGN KEY(SK_EVENTO) REFERENCES DIM_SEDE(SK_SEDE),
    CONSTRAINT CNST_FK_EVENTO_DIM_TIEMPO FOREIGN KEY(SK_FEC_EVENTO) REFERENCES DIM_TIEMPO(SK_TIEMPO)
);

CREATE TABLE FACT_EVENTO_STAND(
    SK_EVENTO NUMERIC NOT NULL,
    SK_TIPO_STAND NUMERIC NOT NULL,
    CANTIDAD_ESTIMADA NUMERIC NOT NULL,
    MT2 NUMERIC(10,4) NOT NULL,
    PRECIO NUMERIC(10,4) NOT NULL,

    CONSTRAINT CNST_PK_EVENTO_STAND PRIMARY KEY(SK_EVENTO, SK_TIPO_STAND),
    CONSTRAINT CNST_FK_EVENTO_STAND_DIM_EVENTO FOREIGN KEY(SK_EVENTO) REFERENCES DIM_EVENTO(SK_EVENTO),
    CONSTRAINT CNST_FK_EVENTO_STAND_DIM_TIPO_STAND FOREIGN KEY(SK_TIPO_STAND) REFERENCES DIM_TIPO_STAND(SK_TIPO_STAND)
);

CREATE TABLE FACT_ALQUILER(
    SK_EVENTO NUMERIC NOT NULL,
    SK_CLIENTE NUMERIC NOT NULL,
    SK_FEC_ALQUILER NUMERIC NOT NULL,
    SK_TIPO_STAND NUMERIC NOT NULL,
    SK_CATEGORIA NUMERIC NOT NULL,
    NUM_CONTRATO NUMERIC NOT NULL,
    NUM_STAND NUMERIC NOT NULL,
    MT2 NUMERIC(10,4) NOT NULL,
    MONTO NUMERIC(10,4) NOT NULL,
    CANTIDAD NUMERIC NOT NULL,

    CONSTRAINT CNST_PK_ALQUILER PRIMARY KEY(SK_EVENTO, SK_CLIENTE, SK_FEC_ALQUILER, SK_TIPO_STAND, SK_CATEGORIA, NUM_CONTRATO, NUM_STAND),
    CONSTRAINT CNST_FK_ALQUILER_DIM_EVENTO FOREIGN KEY(SK_EVENTO) REFERENCES DIM_EVENTO(SK_EVENTO),
    CONSTRAINT CNST_FK_ALQUILER_DIM_CLIENTE FOREIGN KEY(SK_CLIENTE) REFERENCES DIM_CLIENTE(SK_CLIENTE),
    CONSTRAINT CNST_FK_ALQUILER_DIM_FEC_ALQUILER FOREIGN KEY(SK_FEC_ALQUILER) REFERENCES DIM_TIEMPO(SK_TIEMPO),
    CONSTRAINT CNST_FK_ALQUILER_DIM_TIPO_STAND FOREIGN KEY(SK_TIPO_STAND) REFERENCES DIM_TIPO_STAND(SK_TIPO_STAND),
    CONSTRAINT CNST_FK_ALQUILER_DIM_CATEGORIA FOREIGN KEY(SK_CATEGORIA) REFERENCES DIM_CATEGORIA(SK_CATEGORIA)
);

CREATE TABLE FACT_VISITA(
    SK_EVENTO NUMERIC NOT NULL,
    SK_VISITANTE NUMERIC NOT NULL,
    SK_FEC_ALQUILER NUMERIC NOT NULL,
    SK_LEYENDA_ESTRELLAS NUMERIC NOT NULL,
    NUM_ENTRADA NUMERIC NOT NULL,
    HORA_ENTRADA TIMESTAMP NOT NULL,
    CANTIDAD_VISITA NUMERIC NOT NULL,
    CALIFICACION VARCHAR(10) NOT NULL,
    RECOMIENDA_AMIGO VARCHAR(100) NOT NULL,

    CONSTRAINT CNST_PK_VISITA PRIMARY KEY(SK_EVENTO, SK_VISITANTE, SK_FEC_ALQUILER, SK_LEYENDA_ESTRELLAS, NUM_ENTRADA),
    CONSTRAINT CNST_FK_VISITA_DIM_EVENTO FOREIGN KEY(SK_EVENTO) REFERENCES DIM_EVENTO(SK_EVENTO),
    CONSTRAINT CNST_FK_VISITA_DIM_VISITANTE FOREIGN KEY(SK_VISITANTE) REFERENCES DIM_VISITANTE(SK_VISITANTE),
    CONSTRAINT CNST_FK_VISITA_DIM_FEC_ALQUILER FOREIGN KEY(SK_FEC_ALQUILER) REFERENCES DIM_TIEMPO(SK_TIEMPO),
    CONSTRAINT CNST_FK_VISITA_DIM_LEYENDA FOREIGN KEY(SK_LEYENDA_ESTRELLAS) REFERENCES DIM_LEYENDA(SK_LEYENDA)
);