CREATE TABLE PAIS(
    COD_PAIS NUMERIC(2) NOT NULL,
    NB_PAIS VARCHAR(30) NOT NULL,

    CONSTRAINT PK_PAIS PRIMARY KEY(COD_PAIS)
);

CREATE TABLE CIUDAD(
    COD_CIUDAD NUMERIC(4) NOT NULL,
    NB_CIUDAD VARCHAR(30) NOT NULL,
    COD_PAIS NUMERIC(2) NOT NULL,

    CONSTRAINT PK_CIUDAD PRIMARY KEY(COD_CIUDAD),
    CONSTRAINT FK_CIUDAD_PAIS FOREIGN KEY(COD_PAIS) REFERENCES PAIS(COD_PAIS)
);

CREATE TABLE SEDE(
    COD_SEDE NUMERIC(6) NOT NULL,
    NB_SEDE VARCHAR(60) NOT NULL,
    COD_CIUDAD NUMERIC(4) NOT NULL,

    CONSTRAINT PK_SEDE PRIMARY KEY(COD_SEDE),
    CONSTRAINT FK_SEDE_CIUDAD FOREIGN KEY(COD_CIUDAD) REFERENCES CIUDAD(COD_CIUDAD)
);

CREATE TABLE TIPO_EVENTO(
    COD_TIPO_EVENTO NUMERIC(1) NOT NULL,
    NB_TIPO_EVENTO VARCHAR(10) NOT NULL,

    CONSTRAINT PK_TIPO_EVENTO PRIMARY KEY(COD_TIPO_EVENTO)
);

CREATE TABLE EVENTO(
    COD_EVENTO NUMERIC(6) NOT NULL,
    NB_EVENTO VARCHAR(60) NOT NULL,
    FECHA_INICIO DATE NOT NULL,
    FECHA_FIN DATE NOT NULL,
    DESCRIPCION VARCHAR(100),
    COD_SEDE NUMERIC(6) NOT NULL,
    EMAIL VARCHAR(60) NOT NULL,
    COD_TIPO_EVENTO NUMERIC(1) NOT NULL,

    CONSTRAINT PK_EVENTO PRIMARY KEY(COD_EVENTO),
    CONSTRAINT FK_EVENTO_SEDE FOREIGN KEY(COD_SEDE) REFERENCES SEDE(COD_SEDE),
    CONSTRAINT FK_EVENTO_TIPO_EVENTO FOREIGN KEY(COD_TIPO_EVENTO) REFERENCES TIPO_EVENTO(COD_TIPO_EVENTO)
);

CREATE TABLE TIPO_STAND(
    COD_TIPO_STAND NUMERIC(1) NOT NULL,
    NB_TIPO_STAND VARCHAR(16) NOT NULL,

    CONSTRAINT PK_TIPO_STAND PRIMARY KEY(COD_TIPO_STAND)
);

CREATE TABLE EVENTO_STAND(
    COD_EVENTO NUMERIC(6) NOT NULL,
    COD_TIPO_STAND NUMERIC(1) NOT NULL,
    CANTIDAD_ESTIMADA NUMERIC(4) NOT NULL,
    MTS2 NUMERIC(10,4) NOT NULL,
    PRECIO NUMERIC(10,2) NOT NULL,

    CONSTRAINT PK_EVENTO_STAND PRIMARY KEY(COD_EVENTO, COD_TIPO_STAND),
    CONSTRAINT FK_EVENTO_STAND_EVENTO FOREIGN KEY(COD_EVENTO) REFERENCES EVENTO(COD_EVENTO),
    CONSTRAINT FK_EVENTO_STAND_TIPO_STAND FOREIGN KEY(COD_TIPO_STAND) REFERENCES TIPO_STAND(COD_TIPO_STAND)
);

CREATE TABLE CATEGORIA(
    COD_CATEGORIA NUMERIC(2) NOT NULL,
    NB_CATEGORIA VARCHAR(30) NOT NULL,

    CONSTRAINT PK_CATEGORIA PRIMARY KEY(COD_CATEGORIA)
);

CREATE TABLE SUBCATEGORIA(
    COD_SUB_CATEGORIA NUMERIC(3) NOT NULL,
    NB_SUB_CATEGORIA VARCHAR(30) NOT NULL,
    COD_CATEGORIA NUMERIC(2) NOT NULL,

    CONSTRAINT PK_SUB_CATEGORIA PRIMARY KEY(COD_SUB_CATEGORIA),
    CONSTRAINT FK_SUB_CATEGORIA_CATEGORIA FOREIGN KEY(COD_CATEGORIA) REFERENCES CATEGORIA(COD_CATEGORIA)
);

CREATE TABLE CLIENTE(
    COD_CLIENTE NUMERIC(6) NOT NULL,
    NB_CLIENTE VARCHAR(80) NOT NULL,
    CI_RIF VARCHAR(15) NOT NULL,
    TELEFONO VARCHAR(10) NOT NULL,
    DIRECCION VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(60) NOT NULL,

    CONSTRAINT PK_CLIENTE PRIMARY KEY(COD_CLIENTE)
);

CREATE TABLE CONTRATO(
    NRO_STAND NUMERIC(4) NOT NULL,
    COD_EVENTO NUMERIC(6) NOT NULL,
    COD_TIPO_STAND NUMERIC(1) NOT NULL,
    FECHA_ALQUILER DATE NOT NULL,
    COD_CLIENTE NUMERIC(6) NOT NULL,
    MTS2 NUMERIC(10,4) NOT NULL,
    MONTO NUMERIC(10,2) NOT NULL,
    COD_SUB_CATEGORIA NUMERIC(3) NOT NULL,

    CONSTRAINT PK_CONTRATO PRIMARY KEY(NRO_STAND, COD_EVENTO, COD_TIPO_STAND),
    CONSTRAINT FK_CONTRATO_EVENTO_STAND FOREIGN KEY(COD_EVENTO, COD_TIPO_STAND) REFERENCES EVENTO_STAND(COD_EVENTO, COD_TIPO_STAND)
);

CREATE TABLE VISITANTE(
    COD_VISITANTE NUMERIC(8) NOT NULL,
    CEDULA VARCHAR(10) NOT NULL,
    NB_VISITANTE VARCHAR(80) NOT NULL,
    SEXO CHAR(1) NOT NULL,
    EMAIL VARCHAR(60) NOT NULL,

    CONSTRAINT PK_VISITANTE PRIMARY KEY(COD_VISITANTE)
);

CREATE TABLE LEYENDA_ESTRELLAS(
    COD_LEYENDA_ESTRELLAS NUMERIC(1) NOT NULL,
    NB_DESCRIPCION VARCHAR(9) NOT NULL,

    CONSTRAINT PK_LEYENDA_ESTRELLAS PRIMARY KEY(COD_LEYENDA_ESTRELLAS)
);

CREATE TABLE ENTRADA(
    NRO_ENTRADA NUMERIC(10) NOT NULL,
    COD_EVENTO NUMERIC(6) NOT NULL,
    FECHA_ENTRADA DATE NOT NULL,
    HORA_ENTRADA TIMESTAMP NOT NULL,
    COD_VISITANTE NUMERIC(8) NOT NULL,
    RECOMIENDA_AMIGO BOOLEAN,
    CALIFICACION VARCHAR(200),
    COD_LEYENDA_ESTRELLAS NUMERIC(1),

    CONSTRAINT PK_ENTRADA PRIMARY KEY(NRO_ENTRADA),
    CONSTRAINT FK_ENTRADA_EVENTO FOREIGN KEY(COD_EVENTO) REFERENCES EVENTO(COD_EVENTO),
    CONSTRAINT FK_ENTRADA_VISITANTE FOREIGN KEY(COD_VISITANTE) REFERENCES VISITANTE(COD_VISITANTE),
    CONSTRAINT FK_ENTRADA_LEYENDA_ESTRELLAS FOREIGN KEY(COD_LEYENDA_ESTRELLAS) REFERENCES LEYENDA_ESTRELLAS(COD_LEYENDA_ESTRELLAS)
);